version: '{branch}-build-{build}'

shallow_clone: true

install:
  - cd Perl\Scripts
  - .\install-gnu-utilities-collection.bat
  - .\install-strawberry-perl.bat
  - .\install-perl-modules-and-dependencies.bat
  - .\delete-perl-modules-and-dependencies-temporary-files.bat
  - cd ..\..

test: off

build_script:
  - cd Perl\Scripts
  - .\build-strawberry-perl-package-for-fusioninventory-agent.bat
  - cd ..
  - dir Strawberry

artifacts:
  - path: Perl/Strawberry/*.log
    name: logs
  - path: Perl/Strawberry/*.txt
    name: txts
  - path: Perl/Strawberry/*.xz
    name: archives
  - path: Perl/Strawberry/*.md5,Perl/Strawberry/*.sha1,Perl/Strawberry/*.sha256
    name: digests

