version: '{branch}-test-{build}'

shallow_clone: true

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - cinst pandoc --version 1.17.0.2
  - cd Perl\Scripts
  - .\install-gnu-utilities-collection.bat
  - .\install-strawberry-perl-package-for-fusioninventory-agent.bat
  - .\install-fusioninventory-agent.bat
  - .\patch-fusioninventory-agent.bat
  - .\update-ids-repositories.bat
  - cd ..\..

test: off

build_script:
  - cd NSIS
  - .\FusionInventory-Agent.bat
  - dir

artifacts:
  - path: NSIS/*.txt,Perl/Scripts/*build.log*
    name: logs
  - path: NSIS/*.exe
    name: exes
  - path: NSIS/*.md5,NSIS/*.sha1,NSIS/*.sha256
    name: chks

