version: '{branch}-build-{build}'

shallow_clone: true

install:
  - appveyor DownloadFile https://nmap.org/npcap/dist/npcap-0.96.exe
  - .\npcap-0.96.exe /S /loopback_support=no
  - cd Perl\Scripts
  - .\install-gnu-utilities-collection.bat
  - .\update-gnu-utilities-collection.bat

test: off

build_script:
  - .\install-strawberry-perl.bat
  - .\install-perl-modules-and-dependencies.bat
  - .\delete-perl-modules-and-dependencies-temporary-files.bat
  - .\build-strawberry-perl-package-for-fusioninventory-agent.bat
  - cd ..\..
  - dir Perl\Strawberry

artifacts:
  - path: Perl/Strawberry/*.log
    name: logs
  - path: Perl/Strawberry/*.xz
    name: archives
  - path: Perl/Strawberry/*.xz.md5,Perl/Strawberry/*.xz.sha1,Perl/Strawberry/*.xz.sha256
    name: digests

